using System.Collections.Generic;

namespace WinLicApp
{
    public enum Lang { EN, VIE }

    /// <summary>Complete EN / VIE string table for WinLic Manager.</summary>
    public static class L
    {
        public static Lang Current { get; set; } = Lang.VIE;

        private static readonly Dictionary<string, (string EN, string VIE)> S = new()
        {
            // ── Window / header ─────────────────────────────────────────────────
            ["AppTitle"]         = ("Windows Licensing & Information Manager",
                                    "Trình Quản Lý Bản Quyền Windows"),
            ["AdminOk"]          = ("✔  Running as Administrator — all features available",
                                    "✔  Đang chạy với quyền Quản trị viên — đầy đủ tính năng"),
            ["AdminWarn"]        = ("⚠  Not running as Administrator — options 2, 3, 4 require elevation",
                                    "⚠  Chưa có quyền Quản trị viên — tùy chọn 2, 3, 4 cần nâng quyền"),
            ["BtnElevate"]       = ("⚡ Relaunch as Admin",    "⚡ Khởi Chạy Lại Với Quyền Admin"),
            ["BtnAbout"]         = ("About",                   "Giới Thiệu"),

            // ── About dialog ─────────────────────────────────────────────────────
            ["About_Title"]         = ("About — WinLic Manager",
                                      "Giới thiệu — WinLic Manager"),
            ["About_Version"]           = ("v1.5",              "v1.5"),
            ["About_Author"]        = ("Author",                    "Tác giả"),
            ["About_GitHub"]        = ("GitHub",                    "GitHub"),
            ["About_Repo"]          = ("Repository",                "Kho mã nguồn"),
            ["About_Close"]         = ("Close",                     "Đóng"),
            ["About_Desc"]          = ("A graphical Windows licensing management utility for inspecting product keys, activation status, BIOS OEM keys, and managing Windows Software Licensing (slmgr).",
                                      "Công cụ quản lý bản quyền Windows với giao diện đồ họa — hỗ trợ xem Key Bản Quyền, trạng thái kích hoạt, Key OEM BIOS, và quản lý dịch vụ cấp phép Windows (slmgr)."),
            ["About_CheckingVer"]   = ("Checking for updates…",     "Đang kiểm tra cập nhật…"),
            ["About_UpToDate"]      = ("✔ You are on the latest version.",
                                      "✔ Bạn đang dùng phiên bản mới nhất."),
            ["About_NewVer"]        = ("↑ New version available: ", "↑ Có phiên bản mới: "),
            ["About_VerError"]      = ("Could not check for updates.", "Không thể kiểm tra cập nhật."),

            // ── Sidebar button labels ─────────────────────────────────────────────
            ["Btn1"]             = ("1 — Full System & License Info",              "1 — Thông tin Hệ thống & Bản quyền"),
            ["Btn2"]             = ("2 — Test & Install New Product Key",          "2 — Kiểm thử & Cài Key Mới"),
            ["Btn3"]             = ("3 — Remove Activation",                       "3 — Gỡ Kích Hoạt"),
            ["Btn4"]             = ("4 — Reset Activation (Rearm)",                "4 — Đặt Lại Kích Hoạt (Rearm)"),
            ["Btn5"]             = ("5 — 3rd Party Activation Audit",              "5 — Kiểm Tra Kích Hoạt Bên Thứ Ba"),
            ["BtnAuditSettings"] = ("⚙  Audit Scan Settings",                     "⚙  Cài đặt Kiểm tra"),
            ["BtnClear"]         = ("Clear Log",                                   "Xóa nhật ký"),
            ["ChkShowKey"]       = ("Show Full Keys",                              "Hiển thị Key đầy đủ"),

            // ── Log action headers ───────────────────────────────────────────────
            ["Act1"]             = ("Option 1 — Full System & License Info",
                                    "Tùy chọn 1 — Thông tin Hệ thống & Bản quyền"),
            ["Act1_DliHeader"]   = ("License Channel Info  (slmgr /dli)",
                                    "Thông tin Kênh Bản Quyền  (slmgr /dli)"),
            ["Act2"]             = ("Option 2 — Test & Install New Product Key",
                                    "Tùy chọn 2 — Kiểm thử & Cài Key Mới"),
            ["Act3"]             = ("Option 3 — Remove Activation",
                                    "Tùy chọn 3 — Gỡ Kích Hoạt"),
            ["Act4"]             = ("Option 4 — Reset Activation / Rearm",
                                    "Tùy chọn 4 — Đặt Lại Kích Hoạt / Rearm"),
            ["Act5"]             = ("Option 5 — 3rd Party Activation Audit",
                                    "Tùy chọn 5 — Kiểm Tra Kích Hoạt Bên Thứ Ba"),

            // ── Elevation / admin ─────────────────────────────────────────────────
            ["ElevateTitle"]     = ("Elevation Required", "Yêu Cầu Quyền Admin"),
            ["ElevateFail"]      = ("Elevation failed: ", "Không thể yêu cầu nâng quyền: "),
            ["ElevateFromOption"] = ("This option requires Administrator privileges.\n\nRelaunch WinLic Manager as Administrator now?\n\nNote: The previous session log will be preserved.",
                                    "Tùy chọn này yêu cầu quyền Quản trị viên.\n\nKhởi chạy lại WinLic Manager với quyền Admin ngay bây giờ?\n\nLưu ý: Nhật ký phiên trước sẽ được giữ lại."),

            // ── Dialog titles (shared) ────────────────────────────────────────────
            ["Confirm_Title"]    = ("Confirm",      "Xác nhận"),

            // ── Status bar / general ──────────────────────────────────────────────
            ["Ready"]            = ("Ready",        "Sẵn sàng"),
            ["LogCleared"]       = ("Log cleared.", "Đã xóa nhật ký."),
            ["Startup_Ready"]    = ("WinLic Manager {0} — ready.",
                                    "WinLic Manager {0} — sẵn sàng."),
            ["LogRestored"]      = ("▲ Log restored from previous session (before elevation)",
                                    "▲ Nhật ký được khôi phục từ phiên trước (trước khi nâng quyền)"),
            ["Startup_NoAdmin"]  = ("Running without Administrator. Option 1 is fully available. Options 2, 3, 4 will prompt for elevation when selected.",
                                    "Không có quyền Quản trị. Tùy chọn 1 hoạt động bình thường. Tùy chọn 2, 3, 4 sẽ yêu cầu nâng quyền khi được chọn."),

            // ── InputDialog buttons ───────────────────────────────────────────────
            ["Dialog_OK"]        = ("OK",       "Xác nhận"),
            ["Dialog_Cancel"]    = ("Cancel",   "Hủy"),

            // ── Fetch messages ────────────────────────────────────────────────────
            ["Fetch_OS"]         = ("Querying OS information…",
                                    "Đang truy vấn thông tin hệ điều hành…"),
            ["Fetch_BiosKey"]    = ("Checking BIOS/UEFI firmware OEM key…",
                                    "Đang kiểm tra Key Bản Quyền OEM trên BIOS/UEFI…"),
            ["Fetch_License"]    = ("Querying active Windows license (WMI)…",
                                    "Đang truy vấn bản quyền Windows đang hoạt động (WMI)…"),
            ["Fetch_SlmgrNotFound"] = ("slmgr.vbs not found: {0}",
                                       "Không tìm thấy slmgr.vbs: {0}"),
            ["Fetch_RegKey"]     = ("Reading registry backup key…",
                                    "Đang đọc Key Bản Quyền dự phòng từ Registry…"),

            // ── Data labels (LogData) ─────────────────────────────────────────────
            ["D_OsEdition"]      = ("OS Edition:",           "Phiên bản Windows:"),
            ["D_Version"]        = ("Version:",              "Số phiên bản:"),
            ["D_Build"]          = ("Build:",                "Số build:"),
            ["D_Arch"]           = ("Architecture:",         "Kiến trúc hệ thống:"),
            ["D_Edition"]        = ("Edition:",              "Ấn bản:"),
            ["D_Channel"]        = ("Channel:",              "Kênh phân phối:"),
            ["D_PartialKey"]     = ("Partial Key:",          "Key một phần:"),
            ["D_BiosOemKey"]     = ("BIOS OEM Key:",         "Key Bản Quyền OEM BIOS:"),
            ["D_RegBackupKey"]   = ("Registry Backup Key:",  "Key Dự phòng (Registry):"),
            ["D_InstalledKey"]   = ("Installed Key:",        "Key Đã cài đặt:"),
            ["Fetch_InstalledKey"] = ("Decoding installed key from registry…",
                                      "Đang giải mã Key Bản Quyền từ Registry…"),
            ["Fetch_RegPidGenX"]  = ("Analyzing Registry Backup Key via pidgenx...",
                                     "Đang phân tích Key Dự phòng qua pidgenx..."),
            ["Fetch_InstPidGenX"] = ("Analyzing Installed Key via pidgenx...",
                                     "Đang phân tích Key Đã Cài Đặt qua pidgenx..."),

            // ── BIOS OEM key inline pidgenx analysis ──────────────────────────────────────
            ["Fetch_OemPidGenX"]    = ("Running Phase 1 analysis on BIOS OEM key…",
                                      "Đang phân tích Giai đoạn 1 trên Key OEM BIOS…"),
            ["OemPid_Channel"]      = ("  Channel  : ",   "  Kênh     : "),
            ["OemPid_Edition"]      = ("  Edition  : ",   "  Ấn bản   : "),
            ["OemPid_WinVer"]       = ("  Win Ver. : ",   "  Phiên bản: "),
            ["OemPid_Rejected"]     = ("  PidGenX  : Key not found in pkeyconfig.xrm-ms (possibly a pre-Windows 10 OEM key)",
                                      "  PidGenX  : Key không tìm thấy trong pkeyconfig.xrm-ms (có thể là key OEM trước Windows 10)"),
            ["OemPid_FormatOnly"]   = ("  Source   : format check only (pkeyconfig.xrm-ms not found)",
                                      "  Nguồn    : chỉ kiểm tra định dạng (không tìm thấy pkeyconfig.xrm-ms)"),

            // ── License status texts ──────────────────────────────────────────────
            ["LS_0"]             = ("Unlicensed",                     "Chưa được cấp phép"),
            ["LS_1"]             = ("Licensed (Permanently Activated)","Đã được cấp phép (Kích hoạt vĩnh viễn)"),
            ["LS_2"]             = ("OOB Grace Period",               "Thời gian ân hạn OOB"),
            ["LS_3"]             = ("OOT Grace Period",               "Thời gian ân hạn OOT"),
            ["LS_4"]             = ("Non-Genuine Grace Period",       "Thời gian ân hạn không chính hãng"),
            ["LS_5"]             = ("Notification Mode",              "Chế độ thông báo"),
            ["LS_6"]             = ("Extended Grace Period",          "Thời gian ân hạn mở rộng"),
            ["LS_Unknown"]       = ("Unknown",                        "Không xác định"),


            // ── Digital Entitlement detection ────────────────────────────────────
            ["DE_Confirmed"]        = ("Activation method:  Digital Entitlement (HWID / DE)",
                                      "Phương thức kích hoạt:  Digital Entitlement (HWID / DE)"),
            ["DE_Explain1"]         = ("Windows is activated via a Digital Entitlement recorded on Microsoft servers.",
                                      "Windows được kích hoạt qua Digital Entitlement lưu trên máy chủ Microsoft."),
            ["DE_Explain2"]         = ("Bound to your hardware fingerprint and Microsoft Account.",
                                      "Gắn với dấu vân tay phần cứng và tài khoản Microsoft của bạn."),
            ["DE_Explain3"]         = ("The active key is a generic placeholder — the actual entitlement lives in the cloud.",
                                      "Key đang dùng là key chung thay thế — quyền kích hoạt thực sự nằm trên cloud."),
            ["DE_Explain3_Real"]    = ("The installed key appears to be a real retail/OEM key — not a generic placeholder. " +
                                      "Microsoft likely cloud-assigned a Digital Entitlement tied to your hardware and account, " +
                                      "while the original key was preserved.",
                                      "Key đã cài đặt có vẻ là key thực (bán lẻ/OEM) — không phải key chung thay thế. " +
                                      "Microsoft có thể đã gán Digital Entitlement qua đám mây gắn với phần cứng " +
                                      "và tài khoản của bạn, trong khi key gốc được giữ nguyên."),
            ["DE_KeyMismatch"]      = ("The BIOS OEM key and Registry Backup key may differ from the active key. The Registry Backup key (BackupProductKeyDefault) is a pre-existing value placed by Windows Setup, OEM provisioning, or a prior upgrade — it is NOT the key displaced by your most recent install. slmgr /ipk does not reliably update this value. You may be seeing it for the first time because WinLic reads and exposes it.",
                                       "Key OEM BIOS và Key Dự phòng có thể khác Key đang dùng. Key Dự phòng (BackupProductKeyDefault) là giá trị có sẵn từ trước, được đặt bởi Windows Setup, OEM, hoặc lần nâng cấp trước — KHÔNG phải key bị thay thế trong lần cài đặt vừa rồi. slmgr /ipk không cập nhật giá trị này một cách đáng tin cậy. Đây có thể là lần đầu tiên bạn thấy nó vì WinLic đọc và hiển thị nó."),
            ["DE_Verify"]           = ("To verify: Settings > System > Activation > look for Digital license",
                                      "Để xác nhận: Cài đặt > Hệ thống > Kích hoạt > tìm 'Giấy phép kỹ thuật số'"),
            ["DE_NotActivated"]     = ("Activation method:  Digital Entitlement placeholder key detected — but status is NOT Licensed.",
                                      "Phương thức kích hoạt:  Phát hiện key chung DE — nhưng trạng thái KHÔNG được kích hoạt."),
            ["KMS_Detected"]        = ("Activation method:  KMS (Volume/Corporate License)",
                                      "Phương thức kích hoạt:  KMS (Bản quyền doanh nghiệp/tập thể)"),
            ["KMS_Server"]          = ("KMS Server:",                  "Máy chủ KMS:"),
            ["MAK_Detected"]        = ("Activation method:  MAK / Retail / OEM key (standard activation)",
                                      "Phương thức kích hoạt:  MAK / Retail / OEM (kích hoạt tiêu chuẩn)"),

            // ── Option 2 ──────────────────────────────────────────────────────────
            ["O2_Note"]            = ("Note: slmgr /dli shows a summary of the active license. Only the last 5 characters of the product key are revealed.",
                                      "Lưu ý: slmgr /dli hiển thị tóm tắt bản quyền đang hoạt động. Chỉ 5 ký tự cuối của Key Bản Quyền được hiển thị."),
            ["O2_NoOutput"]        = ("No output received from slmgr /dli.",
                                      "Không nhận được kết quả từ slmgr /dli."),
            ["O2_LicenseStatus"]   = ("License Status:  ", "Trạng thái bản quyền:  "),

            // ── Option 3 ──────────────────────────────────────────────────────────
            ["O3_NoLicense"]       = ("No active Windows product license found via WMI.",
                                      "Không tìm thấy bản quyền Windows đang hoạt động qua WMI."),
            ["O3_BiosNone"]        = ("None detected",  "Không phát hiện"),
            ["O3_BiosDetected"]    = ("Detected",     "Đã phát hiện"),
            ["O3_RegNone"]         = ("None found",     "Không tìm thấy"),
            ["O3_KeyBios"]         = ("BIOS OEM Key:          ",  "Key OEM BIOS:          "),
            ["O3_KeyReg"]          = ("Registry Backup Key:   ",  "Key Dự phòng (Registry):  "),
            ["O3_KeyInstalled"]    = ("Installed Key:         ",  "Key Đã cài đặt:        "),
            ["O3_Mismatch"]        = ("Registry Backup Key does NOT match the currently active license key.",
                                      "Key Dự phòng trong Registry KHÔNG khớp với Key Bản Quyền đang hoạt động."),
            ["O3_MismatchReason"]  = ("This can happen after an edition upgrade or a change in activation method.",
                                      "Điều này có thể xảy ra sau khi nâng cấp ấn bản hoặc thay đổi phương thức kích hoạt."),
            ["O3_ActivePartial"]   = ("     Active key ends with:          ",  "     Key đang dùng kết thúc với:  "),
            ["O3_BackupEnds"]      = ("     Registry Backup Key ends with:  ",  "     Key Dự phòng Registry kết thúc với:  "),
            ["O3_ConfirmRemove"]   = ("The Registry Backup Key (stored at HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\SoftwareProtectionPlatform → BackupProductKeyDefault) does not match the active key.\n\nThis stale backup key is likely a leftover from a previous activation or edition upgrade.\n\nRemove the stale Registry Backup Key?\n\nNote: Your active Windows activation will NOT be affected — this only removes the backup copy.",
                                      "Key Dự phòng trong Registry (lưu tại HKLM\\...\\SoftwareProtectionPlatform → BackupProductKeyDefault) không khớp với Key đang hoạt động.\n\nKey dự phòng này có thể là tàn dư từ lần kích hoạt hoặc nâng cấp ấn bản trước đó.\n\nXóa Key Dự phòng trong Registry?\n\nLưu ý: Trạng thái kích hoạt Windows hiện tại sẽ KHÔNG bị ảnh hưởng — chỉ xóa bản sao lưu."),
            ["O3_RegKeyRemoved"]   = ("Registry Backup Key removed.",
                                      "Đã xóa Key Dự phòng khỏi Registry."),
            ["O3_NeedAdmin"]       = ("Run as Administrator to remove the stale backup key.",
                                      "Chạy với quyền Administrator để xóa key dự phòng cũ."),
            ["O3_RemoveErr"]       = ("Could not remove key: ",         "Không thể xóa Key Bản Quyền: "),
            ["O3_RegReadErr"]      = ("Registry read error: ",          "Lỗi đọc Registry: "),
            ["O3_KeyMatch"]        = ("Registry Backup Key matches the active product key.",
                                      "Key Dự phòng trong Registry khớp với Key Bản Quyền đang hoạt động."),
            ["O3_Activation"]      = ("Activation:  ", "Kích hoạt:  "),


            // ── Option 4 ──────────────────────────────────────────────────────────
            ["O4_Info1"]           = ("Phase 1 (offline, instant): Key structure is checked immediately — no network, no registry changes.",
                                      "Giai đoạn 1 (ngoại tuyến, tức thì): Cấu trúc key được kiểm tra ngay — không mạng, không thay đổi registry."),
            ["O4_Info2"]           = ("Phase 2 (online): slmgr /ipk runs only after you confirm — this is the real key install.",
                                      "Giai đoạn 2 (trực tuyến): slmgr /ipk chỉ chạy sau khi bạn xác nhận — đây mới là thao tác cài key thực sự."),
            ["O4_Cancelled"]       = ("Canceled — no key entered.",
                                      "Đã hủy — không nhập Key Bản Quyền."),
            ["O4_BadFormat"]       = ("Invalid format. Key must be  XXXXX-XXXXX-XXXXX-XXXXX-XXXXX",
                                      "Định dạng không hợp lệ. Key phải có dạng  XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"),
            ["O4_Installing"]      = ("Installing key:  ",  "Đang cài đặt key:  "),
            ["O4_Success1"]        = ("Key accepted! Windows will attempt online activation automatically.",
                                      "Key Bản Quyền được chấp nhận! Windows sẽ tự động kích hoạt trực tuyến."),
            ["O4_Success2"]        = ("Check activation status with Option 3 or Option 2.",
                                      "Kiểm tra trạng thái kích hoạt ở Tùy chọn 3 hoặc Tùy chọn 2."),
            ["O4_Fail"]            = ("Key was rejected by Windows.",  "Key Bản Quyền bị Windows từ chối."),
            ["O4_DiagGen"]         = ("Generation Mismatch (0xC004E016) — this key is for a different Windows generation (e.g. a Windows 8 key cannot be installed on Windows 10/11). Microsoft does not allow cross-generation installs via slmgr /ipk.",
                                      "Không khớp thế hệ (0xC004E016) — Key này dành cho thế hệ Windows khác (ví dụ: key Windows 8 không cài được trên Windows 10/11). Microsoft không cho phép cài key khác thế hệ qua slmgr /ipk."),
            ["O4_DiagSku"]         = ("Edition Mismatch (0xC004F069) — this key belongs to a different Windows edition (e.g. Home vs Pro). Use a key for the currently installed edition.",
                                      "Không khớp ấn bản (0xC004F069) — Key này thuộc ấn bản Windows khác (ví dụ: Home và Pro). Hãy dùng key đúng với ấn bản đang cài."),
            ["O4_DiagInvalid"]     = ("Invalid Key — the key is invalid or mistyped.",
                                      "Key không hợp lệ — Key Bản Quyền bị sai hoặc nhập nhầm."),
            ["O4_DiagBlocked"]     = ("Blocked Key — this key has been blocklisted by Microsoft.",
                                      "Key bị chặn — Key Bản Quyền này đã bị Microsoft thu hồi."),
            ["O4_DiagGeneral"]     = ("Check the error code for more information.",
                                      "Kiểm tra mã lỗi để biết thêm thông tin."),

            // ── Option 3 — Remove Activation ─────────────────────────────────────
            // Panel UI keys
            ["O3_Remove_Title"]    = ("⚠  Remove Activation",
                                      "⚠  Gỡ Kích Hoạt"),
            ["O3_Remove_Warn1"]    = ("This will uninstall the current Windows product key (slmgr /upk) AND clear it from the registry (slmgr /cpky).",
                                      "Thao tác này sẽ gỡ cài đặt Key Bản Quyền Windows hiện tại (slmgr /upk) VÀ xóa khỏi Registry (slmgr /cpky)."),
            ["O3_Remove_Warn2"]    = ("Windows will become UNACTIVATED. You will need a valid product key to re-activate.",
                                      "Windows sẽ trở thành CHƯA ĐƯỢC KÍCH HOẠT. Bạn cần Key Bản Quyền hợp lệ để kích hoạt lại."),
            ["O3_Remove_TypeOk"]   = ("Type  OK  below to confirm:",
                                      "Nhập  OK  bên dưới để xác nhận:"),
            ["O3_Remove_Hint"]     = ("This action cannot be undone without a valid product key.",
                                      "Hành động này không thể hoàn tác nếu không có Key Bản Quyền hợp lệ."),
            ["O3_Remove_Cancel"]   = ("Cancel",   "Hủy"),
            ["O3_Remove_Confirm"]  = ("Remove Key", "Gỡ Key"),
            ["O3_Remove_BadInput"] = ("Type OK (uppercase) to confirm.", "Nhập OK (chữ hoa) để xác nhận."),
            // Action result keys (shared with log output)
            ["O3_Cancelled"]     = ("Canceled.", "Đã hủy."),
            ["O5_Uninstalling"]    = ("Uninstalling product key  (slmgr /upk)…",
                                      "Đang gỡ cài đặt Key Bản Quyền  (slmgr /upk)…"),
            ["O5_Clearing"]        = ("Clearing key from registry  (slmgr /cpky)…",
                                      "Đang xóa Key Bản Quyền khỏi Registry  (slmgr /cpky)…"),
            ["O5_Done"]            = ("Product key uninstalled and registry cleared.",
                                      "Đã gỡ cài đặt Key Bản Quyền và xóa khỏi Registry."),

            // ── Option 6 ──────────────────────────────────────────────────────────
            ["O6_Rearming"]        = ("Executing  slmgr /rearm…",  "Đang thực thi  slmgr /rearm…"),
            ["O6_Done"]            = ("Rearm complete. Restart your computer for changes to take effect.",
                                      "Rearm hoàn tất. Khởi động lại máy tính để áp dụng thay đổi."),
            ["O6_Restarting"]      = ("Restarting in 5 seconds…",  "Đang khởi động lại sau 5 giây…"),

            // ── Option 1 — /dlv Extended Scan panel ──────────────────────────────
            ["DLV_PANEL_TITLE"]   = ("Extended License Scan  (slmgr /dlv)",
                                      "Quét Bản Quyền Mở Rộng  (slmgr /dlv)"),
            ["DLV_DESC1"]         = ("slmgr /dlv shows detailed information: grace period, KMS count, activation timestamps, and remaining rearm tokens.",
                                      "slmgr /dlv hiển thị thông tin chi tiết: thời gian gia hạn, số lượng KMS, dấu thời gian kích hoạt và số lần rearm còn lại."),
            ["DLV_DESC2"]         = ("The output will be appended to the log. This may take a few seconds.",
                                      "Kết quả sẽ được thêm vào nhật ký. Quá trình này có thể mất vài giây."),
            ["DLV_CANCEL"]        = ("Cancel",             "Hủy"),
            ["DLV_RUN"]           = ("Run Extended Scan",  "Chạy Quét Mở Rộng"),

            // ── Option 4 — Rearm danger panel ─────────────────────────────────────
            ["R4_PANEL_TITLE"]    = ("⚠  Reset Activation  (Rearm)",
                                      "⚠  Đặt Lại Kích Hoạt  (Rearm)"),
            ["R4_WARN1"]          = ("Rearm consumes one activation token. Windows allows approximately 3 total. Once all tokens are used, rearm will fail permanently until Windows is repaired.",
                                      "Rearm tiêu thụ một token kích hoạt. Windows cho phép khoảng 3 lần tổng cộng. Khi hết token, rearm sẽ thất bại vĩnh viễn cho đến khi sửa chữa Windows."),
            ["R4_WARN2"]          = ("A system restart is required for the reset to take effect.",
                                      "Cần khởi động lại hệ thống để áp dụng đặt lại."),
            ["R4_COUNT_LABEL"]    = ("Remaining rearm tokens:",   "Số lần rearm còn lại:"),
            ["R4_CONFIRM_LABEL"]  = ("Type OK to confirm rearm:", "Nhập OK để xác nhận rearm:"),
            ["R4_RESTART_CHECK"]  = ("Restart automatically after rearm", "Tự động khởi động lại sau rearm"),
            ["R4_CANCEL"]         = ("Cancel",         "Hủy"),
            ["R4_CONFIRM"]        = ("Confirm Rearm",  "Xác Nhận Rearm"),
            ["R4_CANCELLED"]      = ("Rearm cancelled.", "Đã hủy rearm."),

            // ── Option 7 — 3rd-party activation audit ────────────────────────────
            // preamble
            ["P7_Header"]        = ("══ WHAT THIS SCAN CHECKS ══",
                                    "══ CÁC KIỂM TRA TRONG LẦN QUÉT NÀY ══"),
            ["P7_CanDetect1"]    = ("① KMS server name / registry → detects LOCAL emulators (KMSpico, vlmcsd…) AND CLOUD piracy KMS services (e.g. msguides.com, public internet KMS hosts)",
                                    "① Tên máy chủ KMS / registry → phát hiện KMS giả lập CỤC BỘ (KMSpico, vlmcsd…) VÀ dịch vụ KMS lậu trên CLOUD (ví dụ msguides.com, máy chủ KMS công cộng)"),
            ["P7_CanDetect2"]    = ("② Localhost port probe → confirms a live local KMS listener is running",
                                    "② Kiểm tra cổng localhost → xác nhận dịch vụ KMS cục bộ đang hoạt động"),
            ["P7_CanDetect3"]    = ("③ System services → residual activation services that survive reboots",
                                    "③ Dịch vụ hệ thống → dịch vụ kích hoạt cài cố định, tồn tại qua các lần khởi động lại"),
            ["P7_CanDetect4"]    = ("④ Scheduled tasks → periodic re-activation tasks common in KMSpico/KMSAuto",
                                    "④ Tác vụ định kỳ → tác vụ tự động kích hoạt lại, phổ biến ở KMSpico/KMSAuto"),
            ["P7_CanDetect5"]    = ("⑤ Known file/folder paths → installation leftovers from common tools",
                                    "⑤ Đường dẫn tập tin/thư mục → phần còn lại sau khi cài đặt công cụ kích hoạt"),
            ["P7_CanDetect6"]    = ("⑥ Running processes → active activation tool processes at scan time",
                                    "⑥ Tiến trình đang chạy → công cụ kích hoạt đang hoạt động tại thời điểm quét"),
            ["P7_CanDetect7"]    = ("⑦ GVLK key + permanent activation → detects TSforge / KMS38 / HWID-piracy activation patterns",
                                    "⑦ Khóa GVLK + kích hoạt vĩnh viễn → phát hiện kiểu kích hoạt TSforge / KMS38 / HWID lậu"),
            ["P7_CanDetect8"]    = ("⑧ Activation expiry anomaly → flags year-2038 (KMS38), far-future (TSforge KMS4k), or 180-day rolling cycle (Online KMS)",
                                    "⑧ Ngày hết hạn kích hoạt bất thường → cảnh báo năm 2038 (KMS38), tương lai xa (TSforge), hoặc chu kỳ 180 ngày (Online KMS)"),
            ["P7_CanDetect9"]    = ("⑨ SPP store file timestamp → LOW CONFIDENCE indicator of TSforge SPP store manipulation",
                                    "⑨ Dấu thời gian tệp kho SPP → dấu hiệu ĐỘ TIN CẬY THẤP về việc TSforge sửa đổi kho SPP"),
            ["P7_LimitHeader"]   = ("══ KNOWN LIMITATIONS — CANNOT DETECT ══",
                                    "══ GIỚI HẠN ĐÃ BIẾT — KHÔNG THỂ PHÁT HIỆN ══"),
            ["P7_Limit1"]        = ("• HWID (MAS): obtains a REAL Microsoft-issued digital entitlement — indistinguishable from a purchased license. Only detectable if the GVLK/placeholder key is still installed.",
                                    "• HWID (MAS): lấy bản quyền kỹ thuật số DO MICROSOFT CẤP — không thể phân biệt với bản quyền mua. Chỉ có thể phát hiện nếu GVLK / key chung vẫn còn cài đặt."),
            ["P7_Limit2"]        = ("• Cleaned activations: if the tool was fully removed after use, all filesystem and registry traces are gone — activation persists but is undetectable.",
                                    "• Kích hoạt đã dọn sạch: nếu công cụ bị gỡ hoàn toàn sau khi dùng, mọi dấu vết đều mất — kích hoạt vẫn còn nhưng không để lại vết."),
            ["P7_Limit3"]        = ("• Legacy SLIC/OEM BIOS patching (Windows Loader era): modifies firmware tables at a level not visible to software analysis.",
                                    "• Vá SLIC/OEM BIOS kiểu cũ (thời Windows Loader): sửa đổi bảng firmware ở mức không thể thấy qua phân tích phần mềm."),
            ["P7_Limit4"]        = ("• Corporate KMS: legitimate enterprise KMS on a private server may trigger some GVLK indicators — always verify with your IT department.",
                                    "• KMS doanh nghiệp: KMS hợp lệ của công ty trên máy chủ nội bộ có thể kích hoạt một số cảnh báo GVLK — luôn xác nhận với bộ phận IT."),

            // per-check context strings
            ["P7_KmsExplain"]    = ("KMS piracy operates in two forms: (1) LOCAL EMULATOR — a fake KMS server (KMSpico, vlmcsd) running on 127.x.x.x that tricks Windows locally; (2) CLOUD SERVICE — a third-party internet KMS host (e.g. km8.msguides.com) that anyone can configure Windows to use. Microsoft does NOT provide public KMS servers — any internet-facing KMS host is an unauthorized activation service.",
                                    "KMS lậu hoạt động dưới hai dạng: (1) GIẢ LẬP CỤC BỘ — máy chủ KMS giả chạy trên 127.x.x.x lừa Windows từ bên trong máy; (2) DỊCH VỤ CLOUD — máy chủ KMS bên thứ ba trên internet (ví dụ km8.msguides.com) mà bất kỳ ai cũng có thể cấu hình. Microsoft KHÔNG cung cấp máy chủ KMS công cộng — bất kỳ máy chủ KMS nào trên internet đều là dịch vụ kích hoạt trái phép."),
            ["P7_Port1688Explain"] = ("KMS activation port(s) listed below are probed on localhost. An open port means a local KMS emulator is actively listening — the strongest single indicator of local KMS-based piracy.",
                                    "Cổng kích hoạt KMS bên dưới được kiểm tra trên localhost. Cổng mở nghĩa là có KMS giả lập đang chạy cục bộ — đây là dấu hiệu đơn lẻ mạnh nhất của kích hoạt KMS lậu."),
            ["P7_ServiceExplain"] = ("KMS emulators often install as Windows services to survive reboots and periodically re-trigger activation. Well-known service names are matched below.",
                                    "KMS giả lập thường cài đặt dưới dạng dịch vụ Windows để tồn tại qua khởi động lại và định kỳ kích hoạt lại. Các tên dịch vụ đã biết được kiểm tra bên dưới."),
            ["P7_TaskExplain"]   = ("Activation tools like KMSpico create scheduled tasks (e.g. 'AutoKMS') that re-activate Windows periodically to prevent grace-period expiry.",
                                    "Công cụ như KMSpico tạo tác vụ định kỳ (ví dụ 'AutoKMS') để kích hoạt lại Windows theo chu kỳ, ngăn hết hạn thời gian ân hạn."),
            ["P7_FileExplain"]   = ("Known installation folders, executables (KMSELDI.exe), and patched system files are checked against a list of known tool locations.",
                                    "Thư mục cài đặt, tập tin thực thi (KMSELDI.exe) và tập tin hệ thống bị vá được kiểm tra đối chiếu danh sách đường dẫn đã biết."),
            ["P7_ProcExplain"]   = ("Some activation tools leave resident processes. This check lists any currently running processes whose names match known activation tools.",
                                    "Một số công cụ kích hoạt để lại tiến trình thường trú. Kiểm tra này liệt kê các tiến trình đang chạy có tên trùng với công cụ đã biết."),

            // scan step labels
            ["Fetch_KmsHost"]    = ("① Checking KMS server name (registry + WMI)…",
                                    "① Kiểm tra tên máy chủ KMS (registry + WMI)…"),
            ["Fetch_Port1688"]   = ("② Probing configured KMS port(s) on localhost…",
                                    "② Kiểm tra cổng KMS đã cấu hình trên localhost…"),
            ["Fetch_Services"]   = ("③ Scanning system services…",
                                    "③ Quét dịch vụ hệ thống…"),
            ["Fetch_Tasks"]      = ("④ Scanning scheduled tasks…",
                                    "④ Quét tác vụ định kỳ…"),
            ["Fetch_Files"]      = ("⑤ Scanning known tool paths…",
                                    "⑤ Quét đường dẫn công cụ đã biết…"),
            ["Fetch_Procs"]      = ("⑥ Scanning running processes…",
                                    "⑥ Quét tiến trình đang chạy…"),
            ["Fetch_ActChannel"] = ("⑦ Checking activation channel and key type (WMI)…",
                                    "⑦ Kiểm tra kênh kích hoạt và loại khóa (WMI)…"),
            ["Fetch_SppEvents"]  = ("⑨ Checking SPP activation event log…",
                                    "⑨ Kiểm tra nhật ký sự kiện kích hoạt SPP…"),

            // scan results
            ["P7_KmsLocal"]      = ("LOCAL KMS EMULATOR — KMS server is pointing to localhost/127.x.x.x!",
                                    "KMS GIẢ LẬP CỤC BỘ — Máy chủ KMS trỏ đến localhost/127.x.x.x!"),
            ["P7_KmsName"]       = ("KMS server configured:",    "Máy chủ KMS đã cấu hình:"),
            ["P7_KmsNone"]       = ("No KMS server configured.", "Không có máy chủ KMS nào được cấu hình."),
            ["P7_KmsCloudPiracy"] = ("CLOUD KMS PIRACY SERVICE DETECTED — this is a public internet KMS server and is NOT operated by Microsoft! Microsoft does not provide public KMS servers. This is an unauthorized third-party activation service.",
                                     "PHÁT HIỆN DỊCH VỤ KMS LẬU TRÊN CLOUD — đây là máy chủ KMS công cộng trên internet và KHÔNG do Microsoft vận hành! Microsoft không cung cấp máy chủ KMS công cộng. Đây là dịch vụ kích hoạt trái phép của bên thứ ba."),
            ["P7_KmsKnownPiracy"] = ("KNOWN PIRACY KMS DOMAIN — this is a recognized third-party activation service, not a Microsoft server!",
                                     "TÊN MIỀN KMS LẬU ĐÃ BIẾT — đây là dịch vụ kích hoạt bên thứ ba đã được nhận dạng, không phải máy chủ của Microsoft!"),
            ["P7_KmsMsOfficial"]  = ("Microsoft Azure KMS endpoint — this is a legitimate Microsoft-operated server.",
                                     "Điểm cuối KMS Azure của Microsoft — đây là máy chủ hợp lệ do Microsoft vận hành."),
            ["P7_KmsMsOfficialNote"] = ("Note: Azure KMS (kms.core.windows.net / azkms.core.windows.net) is only valid inside Microsoft Azure VMs. On a physical or non-Azure machine this configuration is unusual and should be verified.",
                                        "Lưu ý: KMS Azure (kms.core.windows.net / azkms.core.windows.net) chỉ hợp lệ trong máy ảo Microsoft Azure. Trên máy vật lý hoặc máy không phải Azure, cấu hình này bất thường và cần kiểm tra."),
            ["P7_KmsCorporate"]   = ("KMS server is on a private / internal network address — consistent with a legitimate corporate deployment.",
                                     "Máy chủ KMS trên địa chỉ mạng nội bộ — phù hợp với triển khai doanh nghiệp hợp lệ."),
            ["P7_PortOpen"]      = ("Port {0} OPEN on localhost — a local KMS listener is actively running!",
                                    "Cổng {0} ĐANG MỞ trên localhost — có dịch vụ KMS cục bộ đang chạy!"),
            ["P7_PortClosed"]    = ("Port {0} on localhost is closed (no local KMS listener).",
                                    "Cổng {0} trên localhost đã đóng — không có dịch vụ KMS cục bộ."),
            ["P7_KmsBogusIp"]    = ("BOGUS KMS PLACEHOLDER DETECTED — KMS server is set to 10.0.0.10, a non-routable IP used by MAS Online KMS when no renewal task is installed. This prevents Office activation banners but never actually activates Windows legitimately.",
                                    "PHÁT HIỆN IP KMS GIẢ — Máy chủ KMS được đặt thành 10.0.0.10, một IP không thể định tuyến được MAS Online KMS sử dụng khi không cài tác vụ gia hạn. Điều này ngăn thông báo kích hoạt Office nhưng không thực sự kích hoạt Windows hợp lệ."),
            ["P7_OfficeKmsFound"] = ("Office KMS server configured: {0} — flagged as suspicious (piracy domain or external host)",
                                     "Máy chủ KMS Office đã cấu hình: {0} — bị gắn cờ đáng ngờ (tên miền lậu hoặc host bên ngoài)"),

            // ── Layer 7: GVLK + activation channel ─────────────────────────────
            ["P7_GvlkExplain"]        = ("Checks whether the installed Windows product key is a publicly-known Generic Volume License Key (GVLK) or HWID placeholder key. " +
                                            "The activation CHANNEL is also checked: VOLUME_KMSCLIENT channel + GVLK + no renewal countdown → KMS38/TSforge piracy. " +
                                            "RETAIL or OEM_DM channel + GVLK placeholder + permanent → legitimate Digital Entitlement (HWID) activation. " +
                                            "Genuine enterprise KMS clients always have an active 180-day renewal cycle.",
                                          "Kiểm tra xem khóa Windows đã cài đặt có phải là GVLK hoặc khóa HWID placeholder đã biết công khai. " +
                                          "Kênh kích hoạt cũng được kiểm tra: kênh VOLUME_KMSCLIENT + GVLK + không có đếm ngược → không hợp lệ. " +
                                          "Kênh RETAIL hoặc OEM_DM + placeholder + vĩnh viễn → kích hoạt Digital Entitlement (HWID) hợp lệ."),
            ["P7_GvlkPermanentVolume"] = ("LIKELY PIRACY — VOLUME_KMSCLIENT key '{0}' is installed with PERMANENT activation (no KMS renewal countdown). " +
                                            "Legitimate enterprise KMS clients always show an active 180-day countdown. " +
                                            "This pattern matches KMS38 or TSforge (which forges a KMS lease directly into the SPP store).",
                                          "CÓ KHẢ NĂNG LẬU — Khóa VOLUME_KMSCLIENT '{0}' được cài với kích hoạt VĨNH VIỄN (không có đếm ngược gia hạn KMS). " +
                                          "KMS doanh nghiệp hợp lệ luôn hiển thị đếm ngược 180 ngày. Mẫu này khớp với KMS38 hoặc TSforge."),
            ["P7_GvlkDeActivation"]    = ("HWID placeholder key '{0}' detected with channel '{1}' and permanent activation — consistent with legitimate Digital Entitlement (HWID/DE). " +
                                            "Microsoft grants this through the activation server; it is indistinguishable from a retail license here.",
                                          "Phát hiện khóa HWID placeholder '{0}' với kênh '{1}' và kích hoạt vĩnh viễn — phù hợp với kích hoạt Digital Entitlement (HWID/DE) hợp lệ. " +
                                          "Microsoft cấp qua máy chủ kích hoạt; không thể phân biệt với bản quyền mua chính hãng."),
            ["P7_GvlkWithKms"]         = ("GVLK key '{0}' detected with active KMS renewal — consistent with legitimate enterprise KMS activation. Verify the KMS server above.",
                                          "Phát hiện khóa GVLK '{0}' với gia hạn KMS đang hoạt động — phù hợp với kích hoạt KMS doanh nghiệp hợp lệ. Xác minh máy chủ KMS ở trên."),
            ["P7_NoGvlk"]              = ("Installed key is NOT a known GVLK or placeholder key.",
                                          "Khóa đã cài đặt KHÔNG phải là GVLK hoặc khóa placeholder đã biết."),
            ["P7_NoKeyWmi"]             = ("No licensed Windows product key found via WMI.",
                                          "Không tìm thấy khóa sản phẩm Windows có bản quyền qua WMI."),
            ["P7_WmiErr"]               = ("WMI activation channel error: {0}",
                                          "Lỗi kênh kích hoạt WMI: {0}"),

            // ── Layer 8: Expiry analysis ────────────────────────────────────────
            ["P7_ExpiryExplain"] = ("Analyzes the activation expiry / grace period remaining via WMI. Unusual expiry dates are strong indicators of specific piracy methods.",
                                    "Phân tích ngày hết hạn kích hoạt / thời gian ân hạn còn lại qua WMI. Ngày hết hạn bất thường là dấu hiệu mạnh của các phương thức kích hoạt lậu cụ thể."),
            ["P7_Kms38Expiry"]   = ("KMS38 LEGACY ACTIVATION DETECTED — Activation expiry is set to year {0} (≈ 2038-01-19, the maximum 32-bit timestamp). KMS38 is now patched by Microsoft (November 2025 update KB5068861) but pre-patched machines may still show this expiry.",
                                    "PHÁT HIỆN KÍCH HOẠT KMS38 CŨ — Ngày hết hạn kích hoạt được đặt thành năm {0} (≈ 2038-01-19, dấu thời gian 32-bit tối đa). KMS38 hiện đã được Microsoft vá (cập nhật tháng 11/2025 KB5068861) nhưng máy chưa vá vẫn có thể hiển thị ngày hết hạn này."),
            ["P7_TsforgeExpiry"] = ("TSFORGE KMS4K ACTIVATION DETECTED — Activation expiry is set to year {0} (thousands of years in the future). This is the 'KMS4k' sub-method of TSforge, which forges a KMS lease valid for 4000+ years directly into the SPP trusted store.",
                                    "PHÁT HIỆN KÍCH HOẠT TSFORGE KMS4K — Ngày hết hạn kích hoạt được đặt thành năm {0} (hàng nghìn năm trong tương lai). Đây là phương thức con 'KMS4k' của TSforge, giả mạo hợp đồng thuê KMS có hiệu lực 4000+ năm trực tiếp vào kho tin cậy SPP."),
            ["P7_OnlineKms180"]  = ("ONLINE KMS 180-DAY CYCLE — Activation expires in approximately 180 days, consistent with an Online KMS renewal pattern. Combined with an external KMS server configured above, this strongly indicates MAS Online KMS or similar service.",
                                    "CHU KỲ KMS TRỰC TUYẾN 180 NGÀY — Kích hoạt hết hạn sau khoảng 180 ngày, phù hợp với chu kỳ gia hạn Online KMS. Kết hợp với máy chủ KMS bên ngoài được cấu hình ở trên, điều này cho thấy rõ MAS Online KMS hoặc dịch vụ tương tự."),
            ["P7_ExpiryNormal"]  = ("Activation expiry date appears normal.",
                                    "Ngày hết hạn kích hoạt có vẻ bình thường."),
            ["P7_ExpiryPermanent"] = ("Windows reports permanent activation (no expiry countdown).",
                                      "Windows báo cáo kích hoạt vĩnh viễn (không có đếm ngược hết hạn)."),

            // ── Layer 9 (a): TSforge SPP store timestamp ────────────────────────
            ["P7_SppStoreExplain"] = ("TSforge modifies the Windows SPP trusted store files (data.dat) in-place. A LastWriteTime on these files that does not correlate with any Windows Update event is a LOW CONFIDENCE indicator.",
                                      "TSforge sửa đổi trực tiếp các tệp kho tin cậy SPP Windows (data.dat). Dấu LastWriteTime trên các tệp này không tương ứng với bất kỳ sự kiện Windows Update nào là dấu hiệu ĐỘ TIN CẬY THẤP."),
            ["P7_SppStoreModified"] = ("[LOW CONFIDENCE] SPP store file was modified outside a Windows Update context (LastWriteTime: {0}). This MAY indicate TSforge activation, but Windows Update and legitimate troubleshooting can also modify this file. Use slmgr /dlv for further investigation.",
                                       "[ĐỘ TIN CẬY THẤP] Tệp kho SPP đã được sửa đổi ngoài ngữ cảnh Windows Update (LastWriteTime: {0}). Điều này CÓ THỂ cho thấy kích hoạt TSforge, nhưng Windows Update và khắc phục sự cố hợp lệ cũng có thể sửa đổi tệp này. Dùng slmgr /dlv để điều tra thêm."),
            ["P7_SppStoreOk"]    = ("SPP store file timestamp correlates with a recent Windows Update event — no anomaly detected.",
                                    "Dấu thời gian tệp kho SPP tương ứng với sự kiện Windows Update gần đây — không phát hiện bất thường."),
            ["P7_SppStoreNotFound"] = ("SPP store file not found at expected path — cannot check.",
                                       "Không tìm thấy tệp kho SPP tại đường dẫn dự kiến — không thể kiểm tra."),
            ["P7_SppStoreErr"]      = ("SPP store check error: {0}",
                                       "Lỗi kiểm tra kho SPP: {0}"),

            // ── Layer 8 step header (hardcoded in MainWindow, now localized) ──
            ["Fetch_ActExpiry"]     = ("⑧ Analyzing activation expiry (WMI)…",
                                       "⑧ Phân tích ngày hết hạn kích hoạt (WMI)…"),

            // ── Layer 9(b): SPP security event log ─────────────────────────
            ["P7_SppEventsNone"]   = ("No SPP activation security events found in System log.",
                                      "Không tìm thấy sự kiện bảo mật kích hoạt SPP trong nhật ký Hệ thống."),
            ["P7_SppEventsFound"]  = ("Found {0} SPP security event(s) in System log.",
                                      "Tìm thấy {0} sự kiện bảo mật SPP trong nhật ký Hệ thống."),
            ["P7_SppEventsExt"]    = ("SPP event 12290: KMS request to external server: {0}",
                                      "Sự kiện SPP 12290: Yêu cầu KMS đến máy chủ bên ngoài: {0}"),
            ["P7_SppEventsConf"]   = ("This confirms activation via an unauthorized public KMS service.",
                                      "Điều này xác nhận kích hoạt qua dịch vụ KMS công cộng trái phép."),
            ["P7_SppEventsOk"]     = ("SPP events present — no external KMS server address detected in event data.",
                                      "Có sự kiện SPP — không phát hiện địa chỉ máy chủ KMS bên ngoài trong dữ liệu sự kiện."),
            ["P7_SppEventsErr"]    = ("SPP event log check error: {0}",
                                      "Lỗi kiểm tra nhật ký sự kiện SPP: {0}"),

            // ── Summary indicator count ────────────────────────────────────
            ["P7_IndicatorCount"]  = ("  Total indicators flagged: {0}",
                                      "  Tổng số dấu hiệu bị đánh dấu: {0}"),
            ["P7_PhoneChannel"]  = ("ANOMALOUS PHONE ACTIVATION — Windows reports Phone activation channel with no record of a phone activation flow. This is a characteristic indicator of TSforge ZeroCID sub-method.",
                                    "KÍCH HOẠT ĐIỆN THOẠI BẤT THƯỜNG — Windows báo cáo kênh kích hoạt Điện thoại mà không có bản ghi quy trình kích hoạt qua điện thoại. Đây là dấu hiệu đặc trưng của phương thức con TSforge ZeroCID."),

            // ── Legal notice ───────────────────────────────────────────────────
            ["P7_LegalHeader"]   = ("══ ACTIVATION AUDIT — LEGAL NOTICE ══",
                                    "══ KIỂM TRA KÍCH HOẠT — THÔNG BÁO PHÁP LÝ ══"),
            ["P7_LegalLine1"]    = ("Using Windows without a genuine license purchased from Microsoft or an",
                                    "Sử dụng Windows không có bản quyền chính hãng mua từ Microsoft hoặc"),
            ["P7_LegalLine2"]    = ("authorized reseller violates Microsoft's Terms of Service (EULA §4).",
                                    "đại lý được ủy quyền vi phạm Điều khoản dịch vụ của Microsoft (EULA §4)."),
            ["P7_LegalLine3"]    = ("Enterprise / OEM users: verify licensing with your IT department or OEM.",
                                    "Người dùng doanh nghiệp / OEM: xác minh bản quyền với bộ phận IT hoặc OEM."),
            ["P7_LegalLine4"]    = ("Check your genuine license status: https://aka.ms/MyAccount",
                                    "Kiểm tra trạng thái bản quyền chính hãng: https://aka.ms/MyAccount"),
            ["P7_LegalScanLimit"] = ("SCAN LIMITATIONS: HWID via MAS creates a real MS digital license (undetectable). Any tool removed after use leaves no trace. Corporate KMS may trigger some GVLK indicators.",
                                     "GIỚI HẠN QUÉT: HWID qua MAS tạo bản quyền MS thật (không phát hiện được). Công cụ bị gỡ sau khi dùng không để lại dấu vết. KMS doanh nghiệp có thể kích hoạt một số cảnh báo GVLK."),

            // ── Update defaults ────────────────────────────────────────────────
            ["P7_UpdateDefaults"]  = ("↻ Update Defaults",
                                      "↻ Cập nhật mặc định"),
            ["P7_UpdateSuccess"]   = ("✔ Scan defaults updated successfully from GitHub repository.",
                                      "✔ Đã cập nhật mặc định quét thành công từ kho GitHub."),
            ["P7_UpdateFail"]      = ("⚠ Could not update defaults — check internet connection or try again later.",
                                      "⚠ Không thể cập nhật mặc định — kiểm tra kết nối internet hoặc thử lại sau."),
            ["P7_UpdateChecking"]  = ("Checking for updated scan defaults from GitHub…",
                                      "Đang kiểm tra mặc định quét mới từ GitHub…"),

            // KMS DNS / internet check strings
            ["P7_KmsDomainCount"]   = ("KMS piracy domains in scan: {0} built-in + {1} from settings.ini  (total: {2})",
                                       "Tên miền KMS lậu trong lần quét: {0} mặc định + {1} từ settings.ini  (tổng: {2})"),
            ["P7_CheckDns"]         = ("Checking internet access and resolving host via DNS...",
                                       "Đang kiểm tra kết nối internet và phân giải tên miền qua DNS..."),
            ["P7_KmsDnsPrivate"]    = ("  Resolved to private/internal IP — unusual for a cloud KMS domain.",
                                       "  Phân giải thành IP nội bộ/riêng — bất thường cho miền KMS đám mây."),
            ["P7_KmsDnsResolved"]   = ("Resolves to: ",
                                       "Phân giải thành: "),
            ["P7_KmsDnsPublic"]     = ("Confirmed active: domain resolves to a public IP address.",
                                       "Xác nhận đang hoạt động: tên miền phân giải thành địa chỉ IP công cộng."),
            ["P7_KmsDnsNoResolve"]  = ("Cannot resolve host — service may be offline or DNS-blocked.",
                                       "Không thể phân giải tên miền — dịch vụ có thể ngoại tuyến hoặc bị chặn DNS."),
            ["P7_NoInternet"]       = ("No internet access — DNS verification skipped.",
                                       "Không có kết nối internet — bỏ qua bước xác minh DNS."),
            ["P7_ServiceFound"]   = ("Suspicious service detected:",        "Phát hiện dịch vụ đáng ngờ:"),
            ["P7_NoServices"]     = ("No suspicious services found.",       "Không phát hiện dịch vụ đáng ngờ."),
            ["P7_TaskFound"]      = ("Suspicious scheduled task detected:", "Phát hiện tác vụ định kỳ đáng ngờ:"),
            ["P7_NoTasks"]        = ("No suspicious scheduled tasks found.","Không phát hiện tác vụ đáng ngờ."),
            ["P7_FileFound"]      = ("Known activation tool path found:",   "Phát hiện đường dẫn công cụ kích hoạt:"),
            ["P7_NoFiles"]        = ("No known activation tool files found.","Không phát hiện tập tin công cụ."),
            ["P7_ProcFound"]      = ("Suspicious process running:",         "Phát hiện tiến trình đáng ngờ:"),
            ["P7_NoProcs"]        = ("No suspicious processes running.",    "Không phát hiện tiến trình đáng ngờ."),
            ["P7_Clean"]          = ("No 3rd-party activation indicators detected — system appears clean.",
                                    "Không phát hiện dấu hiệu kích hoạt bên thứ ba — hệ thống có vẻ sạch."),
            ["P7_Suspicious"]     = ("One or more suspicious indicators found — review the results above.",
                                    "Phát hiện một hoặc nhiều dấu hiệu đáng ngờ — xem kết quả ở trên."),
            ["P7_Critical"]       = ("CRITICAL: Piracy KMS activation detected (local emulator or unauthorized cloud service). Windows is almost certainly using unauthorized activation.",
                                    "NGHIÊM TRỌNG: Phát hiện kích hoạt KMS lậu (giả lập cục bộ hoặc dịch vụ cloud trái phép). Windows gần như chắc chắn đang dùng kích hoạt không hợp lệ."),
            ["P7_SummaryHeader"]  = ("Results",  "Kết quả"),

            // ── Settings dialog ───────────────────────────────────────────────────
            ["SD_Title"]    = ("Option 7 — Audit Scan Settings",
                               "Tùy chọn 7 — Cài đặt Kiểm tra"),
            ["SD_Desc"]     = ("Customize the scan lists used by the 3rd Party Activation Audit. Built-in defaults cannot be removed. Custom additions are saved to settings.ini next to the application.",
                               "Tùy chỉnh danh sách quét cho Kiểm tra Kích Hoạt Bên Thứ Ba. Mặc định tích hợp sẵn không thể xóa. Bổ sung của người dùng được lưu vào settings.ini cạnh ứng dụng."),
            ["SD_Ports"]    = ("KMS Ports to Probe",              "Cổng KMS cần kiểm tra"),
            ["SD_Services"] = ("Suspicious Service Names",        "Tên dịch vụ đáng ngờ"),
            ["SD_Tasks"]    = ("Suspicious Task Keywords",        "Từ khóa tác vụ đáng ngờ"),
            ["SD_Procs"]    = ("Suspicious Process Names",        "Tên tiến trình đáng ngờ"),
            ["SD_Files"]    = ("Custom File/Folder Paths",        "Đường dẫn tập tin/thư mục tùy chỉnh"),
            ["SD_Defaults"] = ("Built-in defaults (read-only):",  "Mặc định tích hợp sẵn (chỉ đọc):"),
            ["SD_Custom"]   = ("Custom additions (one per line):", "Bổ sung thêm (mỗi dòng một mục):"),
            ["SD_FilesNote"] = ("Built-in file/folder paths are computed from system environment variables at scan time. Add any extra paths here (one per line).",
                                "Đường dẫn tập tin/thư mục mặc định được tính từ biến môi trường hệ thống khi quét. Thêm đường dẫn bổ sung tại đây (mỗi dòng một mục)."),
            ["SD_SaveNote"] = ("Saved to settings.ini alongside the application.",
                               "Lưu vào settings.ini cạnh ứng dụng."),
            ["SD_Save"]     = ("Save",  "Lưu"),
            ["SD_Saved"]    = ("Settings saved to:", "Đã lưu cài đặt vào:"),
            ["SD_GvlkCount"] = ("{0} GVLK key entries loaded from settings.ini",
                                "{0} mục khóa GVLK đã tải từ settings.ini"),

            // ── Settings dialog — Generic / VL keys section ───────────────────────
            ["SD_GenericKeys"]    = ("Generic / VL Placeholder Key Suffixes  (Layer 7 — DE detection)",
                                     "Hậu tố Khóa Chung / Cấp phép Số lượng Lớn  (Lớp 7 — phát hiện DE)"),
            ["SD_GenericDefNote"] = ("Built-in suffixes used to identify HWID/DE placeholder and volume license keys (read-only).",
                                     "Hậu tố tích hợp sẵn dùng để nhận diện khóa HWID/DE và khóa bản quyền số lượng lớn (chỉ đọc)."),
            ["SD_GenericUserNote"] = ("Add your own key suffixes (one  KEY = Description  per line):",
                                     "Thêm hậu tố khóa của bạn (mỗi dòng một  KEY = Mô tả):"),
            ["SD_GenericLink"]    = ("Official Microsoft VL / Generic Key reference:",
                                    "Tài liệu chính thức Microsoft VL / Key chung:"),

            // ── Key Entry Panel (segmented key input, Option 2) ───────────────────
            ["KP_Title"]   = ("Enter Product Key", "Nhập Key Bản Quyền"),
            ["KP_Info1"]   = ("Phase 1 (offline, instant): Key structure is checked as you type — no network, no registry changes.",
                              "Giai đoạn 1 (ngoại tuyến, tức thì): Cấu trúc key được kiểm tra ngay khi nhập — không mạng, không thay đổi registry."),
            ["KP_Info2"]   = ("Phase 2 (online): slmgr /ipk runs only after you type OK and click Install — this is the real key install.",
                              "Giai đoạn 2 (trực tuyến): slmgr /ipk chỉ chạy sau khi bạn nhập OK và nhấn Cài đặt — đây mới là thao tác cài key thực sự."),
            ["KP_Warn"]    = ("⚠  If the key is compatible, it WILL overwrite your current product key immediately.",
                              "⚠  Nếu key tương thích, nó SẼ ghi đè key bản quyền hiện tại ngay lập tức."),
            ["KP_TypeOk"]  = ("Type  OK  below to confirm you understand:",
                              "Nhập  OK  bên dưới để xác nhận bạn đã hiểu:"),
            ["KP_BadInput"] = ("Type OK (uppercase) to confirm before installing.",
                               "Nhập OK (chữ hoa) để xác nhận trước khi cài đặt."),
            ["KP_Hint"]    = ("Your existing activation is NOT affected if the key is rejected.",
                              "Kích hoạt hiện tại KHÔNG bị ảnh hưởng nếu key bị từ chối."),
            ["KP_Install"] = ("Install Key", "Cài đặt Key"),
            ["KP_Cancel"]  = ("Cancel", "Hủy"),

            // ── Key Entry Panel -- PidGenX decode banner ──────────────────────────
            ["KP_PidValid"]    = ("Phase 1 OK — format valid",
                                  "Giai đoạn 1 OK — định dạng hợp lệ"),
            ["KP_PidInvalid"]  = ("Phase 1 FAIL — must be 25 alphanumeric chars in 5x5 groups",
                                  "Giai đoạn 1 THẤT BẠI — phải có 25 ký tự chữ-số chia thành 5 nhóm 5"),
            ["KP_PidRejected"] = ("Phase 1 WARNING — key not recognized by pidgenx for this Windows version",
                                  "Giai đoạn 1 CẢNH BÁO — key không được pidgenx nhận diện cho phiên bản Windows này"),
            ["KP_PidEdition"]  = ("  Edition  : ", "  Ấn bản   : "),
            ["KP_PidChannel"]  = ("  Channel  : ", "  Kênh     : "),
            ["KP_PidPartNo"]   = ("  Part No. : ", "  Mã SP    : "),
            ["KP_PidWinVer"]   = ("  Win Ver. : ", "  Phiên bản: "),

            // ── Option 2 — Phase 1 PidGenX strings ───────────────────────────────
            ["O2_PIDGX_ABOUT"]       = ("Phase 1 — Offline Key Analysis (instant, no network, no registry change): " +
                                        "calls pidgenx.dll (present on all Win10/11) with pkeyconfig.xrm-ms to validate " +
                                        "the key checksum and identify its Channel. Phase 2 (slmgr /ipk) is the final " +
                                        "authority on whether the key actually works for this system.",
                                        "Giai đoạn 1 — Phân tích key ngoại tuyến (tức thì, không mạng, không thay đổi registry): " +
                                        "gọi pidgenx.dll (có sẵn trên mọi Win10/11) với pkeyconfig.xrm-ms để xác thực checksum " +
                                        "và xác định kênh phân phối của key. Giai đoạn 2 (slmgr /ipk) mới là bước kiểm tra thực sự quyết định key có hoạt động trên hệ thống này không."),
            ["O2_PIDGX_HDR"]         = ("-- KEY ANALYSIS -- (Phase 1: Offline)",
                                        "-- PHÂN TÍCH KEY -- (Giai đoạn 1: Ngoại tuyến)"),
            ["O2_PIDGX_VALID"]       = ("Format   : OK (25 alphanumeric chars, 5x5 groups)",
                                        "Định dạng: HỢP LỆ (25 ký tự chữ-số, 5 nhóm 5)"),
            ["O2_PIDGX_REJECTED"]    = ("PidGenX  : REJECTED — key not found in pkeyconfig.xrm-ms for this Windows version",
                                        "PidGenX  : TỪ CHỐI — key không tìm thấy trong pkeyconfig.xrm-ms cho phiên bản Windows này"),
            ["O2_PIDGX_SRC_PIDGENX"] = ("Source   : pidgenx.dll + pkeyconfig.xrm-ms (real key group lookup)",
                                        "Nguồn    : pidgenx.dll + pkeyconfig.xrm-ms (tra cứu key group thực sự)"),
            ["O2_PIDGX_EDITION"]     = ("  Edition  : ",
                                         "  Ấn bản   : "),
            ["O2_PIDGX_PARTNO"]      = ("  Part No. : ",
                                         "  Mã SP    : "),
            ["O2_PIDGX_WINVER"]      = ("  Win Ver. : ",
                                         "  Phiên bản: "),
            ["O2_PIDGX_SRC_CHK"]     = ("Source   : format check only (pidgenx.dll unavailable or key not in pkeyconfig)",
                                        "Nguồn    : chỉ kiểm tra định dạng (pidgenx.dll không khả dụng hoặc key không trong pkeyconfig)"),
            ["O2_PHASE2_HDR"]        = ("── Phase 2: Installing key via slmgr /ipk ──────────────────────────",
                                        "── Giai đoạn 2: Cài đặt key qua slmgr /ipk ──────────────────────"),

            // ── Option 2 — pidgenx-rejected warning dialog ──────────────────
            ["KP_PIDGX_REJECT_TITLE"]   = ("Key Not Recognized — Possible Wrong Windows Version",
                                           "Key Không Được Nhận Diện — Sai Phiên Bản Windows?"),
            ["KP_PIDGX_REJECT_WARN"]    = ("Phase 1 WARNING: This key was NOT found in pkeyconfig.xrm-ms on this system.\n\n" +
                                           "This usually means the key belongs to a different Windows generation (e.g. Windows 7 or 8) " +
                                           "and cannot be installed on Windows 10/11 via slmgr /ipk.\n\n" +
                                           "Do you want to attempt the install anyway? (It will likely fail with 0xC004E016)",
                                           "Cảnh báo Giai đoạn 1: Key KHÔNG tìm thấy trong pkeyconfig.xrm-ms trên hệ thống này.\n\n" +
                                           "Điều này thường có nghĩa key thuộc phiên bản Windows khác (ví dụ Windows 7 hoặc 8) " +
                                           "và không thể cài trên Windows 10/11 qua slmgr /ipk.\n\n" +
                                           "Bạn vẫn muốn thử cài đặt không? (Có thể sẽ thất bại với lỗi 0xC004E016)"),
            ["KP_PIDGX_REJECT_ABORTED"] = ("Install aborted — key not recognized in pkeyconfig for this Windows version.",
                                           "Đã hủy cài đặt — key không được nhận diện trong pkeyconfig cho phiên bản Windows này."),
            ["KP_PIDGX_REJECT_OVERRIDE"]= ("Proceeding at user's request — key was not recognized by pidgenx for this Windows version.",
                                           "Tiếp tục theo yêu cầu người dùng — key không được nhận diện bởi pidgenx cho phiên bản Windows này."),


            // ── Option 2 — save-key advisory for non-generic Retail/MAK/OEM keys ──
            ["O2_SAVE_KEY_WARN"] = ("⚠  This appears to be a unique Retail / MAK / OEM key. " +
                                    "Save it now before installing a new key — " +
                                    "you will NOT be able to recover it afterwards.",
                                    "⚠  Đây có vẻ là key Retail / MAK / OEM riêng. " +
                                    "Hãy lưu lại trước khi cài key mới — " +
                                    "bạn sẽ KHÔNG thể khôi phục sau này."),

            // ── Option 2 — auto /ato after successful /ipk ───────────────────────
            ["O2_ATO_AUTO"]          = ("Attempting online activation automatically (slmgr /ato)...",
                                        "Đang tự động kích hoạt trực tuyến (slmgr /ato)..."),
            ["O2_ATO_SUCCESS"]       = ("Online activation succeeded.",
                                        "Kích hoạt trực tuyến thành công."),
            ["O2_ATO_FAIL"]          = ("Online activation failed. Error:",
                                        "Kích hoạt trực tuyến thất bại. Lỗi:"),
            ["O2_DIAG_DIDNTWORK"]    = ("Diagnosis: Key Did Not Work (0x80070490) — key may be invalid or not accepted by this edition.",
                                        "Chẩn đoán: Key Không Hoạt Động (0x80070490) — key có thể không hợp lệ hoặc không được chấp nhận bởi ấn bản này."),
            ["O2_DIAG_SERVER_INVALID"] = ("Diagnosis: Server Reports Key Invalid (0xC004C001) — Microsoft activation server rejected this MAK. Verify the key.",
                                           "Chẩn đoán: Máy Chủ Báo Key Không Hợp Lệ (0xC004C001) — máy chủ kích hoạt Microsoft từ chối MAK này. Hãy kiểm tra lại key."),
            ["O2_DIAG_MAK_LIMIT"]    = ("Diagnosis: MAK Activation Limit Exceeded (0xC004C020 / 0xC004C021) — this Multiple Activation Key has used all its activations. Contact Microsoft Licensing.",
                                        "Chẩn đoán: Vượt Giới Hạn Kích Hoạt MAK (0xC004C020 / 0xC004C021) — Key Kích Hoạt Nhiều Lần này đã dùng hết số lần kích hoạt. Liên hệ Microsoft Licensing."),
            ["O2_DIAG_SERVER_NOACT"]  = ("Diagnosis: Server Could Not Activate (0xC004B100) — Microsoft server was unable to activate this key. Verify the MAK with Microsoft Licensing.",
                                         "Chẩn đoán: Máy Chủ Không Thể Kích Hoạt (0xC004B100) — máy chủ Microsoft không thể kích hoạt key này. Xác minh MAK với Microsoft Licensing."),
            ["O2_DIAG_GRACE"]        = ("Diagnosis: Grace Period Expired (0xC004F009) — the activation grace period has ended. Contact Microsoft Licensing for assistance.",
                                        "Chẩn đoán: Hết Thời Gian Ân Hạn (0xC004F009) — thời gian ân hạn kích hoạt đã kết thúc. Liên hệ Microsoft Licensing để được hỗ trợ."),
            ["O2_DIAG_NOTGENUINE"]   = ("Diagnosis: Not Genuine Windows (0x8004FE21) — system files may be modified or corrupted. Reinstall Windows.",
                                        "Chẩn đoán: Windows Không Chính Hãng (0x8004FE21) — tệp hệ thống có thể bị thay đổi hoặc hỏng. Cài lại Windows."),

            ["O2_DIAG_NO_NET"]      = ("Diagnosis: No Internet / Server Unreachable (0x8007232B) — Windows could not reach Microsoft activation servers. Check your internet connection and try again.",
                                        "Chẩn đoán: Không Có Internet / Không Kết Được Máy Chủ (0x8007232B) — Windows không thể kết nối đến máy chủ kích hoạt Microsoft. Kiểm tra kết nối internet và thử lại."),
            ["O2_DIAG_KMS_NO_SRV"] = ("Diagnosis: KMS Server Unavailable (0xC004F074) — no KMS host could be contacted. If using a Retail/MAK key, switch to Retail channel first (Option 6). If using KMS, use Option 8 to diagnose.",
                                        "Chẩn đoán: Máy Chủ KMS Không Khả Dụng (0xC004F074) — không thể liên hệ máy chủ KMS. Nếu dùng key Retail/MAK, hãy đổi kênh sang Retail trước (Tùy chọn 6). Nếu dùng KMS, dùng Tùy chọn 8 để chẩn đoán."),
            ["O2_ATO_NO_INTERNET"]  = ("Offline: No internet detected — online activation may fail. Ensure you have an active connection before proceeding.",
                                        "Ngoại tuyến: Không phát hiện kết nối internet — kích hoạt trực tuyến có thể thất bại. Hãy đảm bảo có kết nối trước khi tiếp tục."),
            ["O2_NET_NOTICE"]      = ("Retail / MAK / OEM keys require internet access to activate with Microsoft servers.",
                                       "Key Retail / MAK / OEM yêu cầu kết nối internet để kích hoạt với máy chủ Microsoft."),

            // ── Option 2 — additional /ipk error diagnoses ────────────────────────
            ["O2_DIAG_ACCESS_DENIED"]    = ("Diagnosis: Access Denied (0x80070005) — slmgr requires Administrator privileges. Ensure WinLicApp is running as Administrator.",
                                             "Chẩn đoán: Bị Từ Chối Truy Cập (0x80070005) — slmgr cần quyền Quản trị viên. Đảm bảo WinLicApp đang chạy với quyền Quản trị viên."),
            ["O2_DIAG_KEY_LIMIT"]        = ("Diagnosis: Key Activation Limit Exceeded (0xC004C008) — this key has reached its maximum number of activations. Contact Microsoft Licensing or obtain a new key.",
                                             "Chẩn đoán: Vượt Giới Hạn Kích Hoạt Key (0xC004C008) — key này đã đạt số lần kích hoạt tối đa. Liên hệ Microsoft Licensing hoặc lấy key mới."),
            ["O2_DIAG_VOL_LIC"]          = ("Diagnosis: Volume License Key Requires OEM BIOS Marker (0xC004F035) — this computer's UEFI firmware lacks the required ACPI/SLIC table for a Volume License key. Use a Retail or MAK key instead.",
                                             "Chẩn đoán: Key Volume License Yêu Cầu Dấu Hiệu BIOS OEM (0xC004F035) — firmware UEFI của máy này thiếu bảng ACPI/SLIC cần thiết cho key Volume License. Hãy dùng key Retail hoặc MAK thay thế."),
            ["O2_DIAG_KEY_BLOCKED_SLS"]  = ("Diagnosis: Product Key Blocked at Licensing Level (0xC004F051) — Microsoft's Software Licensing Service has blocklisted this key. Obtain a new key from an authorized source.",
                                             "Chẩn đoán: Key Sản Phẩm Bị Chặn Ở Cấp Cấp Phép (0xC004F051) — Dịch vụ Cấp phép Phần mềm Microsoft đã chặn key này. Lấy key mới từ nguồn được ủy quyền."),

            // ── Option 2 — additional /ato error diagnoses ────────────────────────
            ["O2_DIAG_DNS_NONAME"]       = ("Diagnosis: KMS Server Not Found in DNS (0x8007007B / 0x80092328) — the KMS SRV record is missing. If using Retail/MAK key switch to Retail channel first (Option 6). If enterprise KMS, contact your IT administrator to verify DNS SRV records.",
                                             "Chẩn đoán: Không Tìm Thấy Máy Chủ KMS Trong DNS (0x8007007B / 0x80092328) — bản ghi SRV KMS không tồn tại. Nếu dùng key Retail/MAK hãy chuyển sang kênh Retail trước (Tùy chọn 6). Nếu KMS doanh nghiệp, liên hệ quản trị viên IT kiểm tra bản ghi DNS SRV."),
            ["O2_DIAG_RPC_UNAVAIL"]      = ("Diagnosis: RPC Server Unavailable (0x800706BA) — the KMS host is unreachable or TCP port 1688 is blocked by a firewall. Check network connectivity and firewall rules on both client and server.",
                                             "Chẩn đoán: Máy Chủ RPC Không Khả Dụng (0x800706BA) — máy chủ KMS không thể kết nối hoặc cổng TCP 1688 bị tường lửa chặn. Kiểm tra kết nối mạng và quy tắc tường lửa trên cả client và server."),
            ["O2_DIAG_DNS_FAIL"]         = ("Diagnosis: DNS Server Failure (0x8007232A / 0x8007251D) — the DNS server could not resolve the KMS hostname. Check DNS settings and network connectivity.",
                                             "Chẩn đoán: Lỗi Máy Chủ DNS (0x8007232A / 0x8007251D) — máy chủ DNS không thể phân giải tên máy chủ KMS. Kiểm tra cài đặt DNS và kết nối mạng."),
            ["O2_DIAG_NET_TIMEOUT"]      = ("Diagnosis: Connection Timeout (0x80072EE2 / 0x80072EE7 / 0x80072EFD) — Windows could not reach the activation server. Check internet, disable VPN/proxy, or use phone activation: run 'slui 4'.",
                                             "Chẩn đoán: Hết Thời Gian Kết Nối (0x80072EE2 / 0x80072EE7 / 0x80072EFD) — Windows không thể kết nối đến máy chủ kích hoạt. Kiểm tra internet, tắt VPN/proxy, hoặc dùng kích hoạt qua điện thoại: chạy 'slui 4'."),
            ["O2_DIAG_HW_CHANGED"]       = ("Diagnosis: Hardware Changed (0xC004F00F) — significant hardware changes were detected. Use the Activation Troubleshooter (Settings → Activation) or phone activation ('slui 4'). For digital licenses sign in with the linked Microsoft account.",
                                             "Chẩn đoán: Phần Cứng Đã Thay Đổi (0xC004F00F) — phát hiện thay đổi phần cứng đáng kể. Dùng Trình Khắc Phục Sự Cố Kích Hoạt (Cài đặt → Kích hoạt) hoặc kích hoạt qua điện thoại ('slui 4'). Với giấy phép số, đăng nhập bằng tài khoản Microsoft đã liên kết."),
            ["O2_DIAG_LIC_EVAL_FAIL"]    = ("Diagnosis: License Evaluation Failed (0xC004E003) — the Software Licensing Service cannot evaluate the license. Run 'slmgr /rilc' as Administrator to reinstall license files, then retry activation.",
                                             "Chẩn đoán: Đánh Giá Giấy Phép Thất Bại (0xC004E003) — Dịch vụ Cấp phép Phần mềm không thể đánh giá giấy phép. Chạy 'slmgr /rilc' với quyền Quản trị viên để cài lại tệp giấy phép, sau đó thử kích hoạt lại."),
            ["O2_DIAG_KMS_COUNT"]        = ("Diagnosis: KMS Activation Count Insufficient (0xC004F038) — your KMS server requires at least 25 Windows client activation requests before it will activate any client. Contact your IT administrator.",
                                             "Chẩn đoán: Số Lượng Kích Hoạt KMS Chưa Đủ (0xC004F038) — máy chủ KMS cần ít nhất 25 yêu cầu kích hoạt từ client Windows trước khi kích hoạt bất kỳ máy nào. Liên hệ quản trị viên IT."),
            ["O2_DIAG_KMS_DISABLED"]     = ("Diagnosis: KMS Service Not Enabled / Not Responding (0xC004F039) — the KMS host service is not running or is not responding. Ensure TCP port 1688 is not blocked and the KMS host service is active.",
                                             "Chẩn đoán: Dịch Vụ KMS Chưa Được Bật / Không Phản Hồi (0xC004F039) — dịch vụ KMS trên máy chủ chưa chạy hoặc không phản hồi. Đảm bảo cổng TCP 1688 không bị chặn và dịch vụ KMS đang hoạt động."),
            ["O2_DIAG_KMS_NOT_ACT"]      = ("Diagnosis: KMS Host Not Activated (0xC004F041) — the KMS host server itself has not been activated with Microsoft. The IT administrator must activate the KMS host before clients can activate.",
                                             "Chẩn đoán: Máy Chủ KMS Chưa Được Kích Hoạt (0xC004F041) — bản thân máy chủ KMS chưa được kích hoạt với Microsoft. Quản trị viên IT phải kích hoạt máy chủ KMS trước khi các client có thể kích hoạt."),
            ["O2_DIAG_KMS_WRONG"]        = ("Diagnosis: Wrong KMS Host for This Product (0xC004F042) — the configured KMS server cannot activate this Windows version. Ensure the KMS host version is compatible. Contact your IT administrator.",
                                             "Chẩn đoán: Máy Chủ KMS Sai Cho Sản Phẩm Này (0xC004F042) — máy chủ KMS được cấu hình không thể kích hoạt phiên bản Windows này. Đảm bảo phiên bản máy chủ KMS tương thích. Liên hệ quản trị viên IT."),
            ["O2_DIAG_NONGENUINE_EXP"]   = ("Diagnosis: Non-Genuine Grace Period Expired (0xC004F064) — Windows was not activated in time and has entered Notification state. Enter a valid genuine product key immediately.",
                                             "Chẩn đoán: Hết Thời Gian Ân Hạn Không Chính Hãng (0xC004F064) — Windows chưa được kích hoạt kịp thời và đã vào trạng thái Thông báo. Hãy nhập ngay key sản phẩm chính hãng hợp lệ."),
            ["O2_DIAG_NONGENUINE_GRC"]   = ("Diagnosis: Running in Non-Genuine Grace Period (0xC004F065) — Windows has detected this copy may not be genuine. Activate with a valid key before the grace period ends.",
                                             "Chẩn đoán: Đang Chạy Trong Thời Gian Ân Hạn Không Chính Hãng (0xC004F065) — Windows phát hiện bản sao này có thể không chính hãng. Kích hoạt bằng key hợp lệ trước khi hết thời gian ân hạn."),
            ["O2_DIAG_KMS_CLOCK"]        = ("Diagnosis: KMS Clock Skew Too Large (0xC004F06C) — the system clock differs from the KMS server by more than 4 hours. Synchronize time by running 'w32tm /resync' as Administrator, then retry activation.",
                                             "Chẩn đoán: Đồng Hồ Hệ Thống Lệch Quá Lớn So Với KMS (0xC004F06C) — đồng hồ hệ thống chênh lệch với máy chủ KMS hơn 4 giờ. Đồng bộ hóa thời gian bằng cách chạy 'w32tm /resync' với quyền Quản trị viên, sau đó thử kích hoạt lại."),

            // ── Option 2 — Key Analysis log block (aligned to PS1 output) ─────────
            ["O2_PIDGX_HDR"]     = ("-- KEY ANALYSIS -- (Phase 1: Offline)",
                                    "-- PHÂN TÍCH KEY -- (Giai đoạn 1: Ngoại tuyến)"),
            ["O2_PIDGX_EDITION"] = ("  Edition  : ",  "  Ấn bản   : "),
            ["O2_PIDGX_VALID"]   = ("  Format   : OK (25 alphanumeric chars, 5x5 groups)",
                                    "  Định dạng: HỢP LỆ (25 ký tự chữ-số, 5 nhóm 5)"),

            // ── Sidebar button — Option 6 ─────────────────────────────────────────
            ["Btn6"]             = ("6 — Change Activation Channel",               "6 — Thay Đổi Kênh Kích Hoạt"),
            ["Btn7"]             = ("7 — Check & Remove KMS Settings",             "7 — Kiểm Tra & Xóa Cài Đặt KMS"),
            ["Btn8"]             = ("8 — KMS Activation",                          "8 — Kích Hoạt KMS"),

            // ── Sidebar tabs ───────────────────────────────────────────────────────
            ["TAB_WIN"]          = ("⊞  Windows 10 / 11",  "⊞  Windows 10 / 11"),
            ["TAB_OFFICE"]       = ("☰  Office 2019+",     "☰  Office 2019+"),
            ["TAB_OFFICE_TITLE"] = ("Under Development",    "Đang Phát Triển"),
            ["TAB_OFFICE_DESC"]  = ("Office 2019/2021/2024 activation management is planned for a future release. Stay tuned!",
                                     "Quản lý kích hoạt Office 2019/2021/2024 đang được lên kế hoạch cho phiên bản tương lai. Hãy đón chờ!"),


            // ── Option 6 — KMS Activation ─────────────────────────────────────────
            ["Act6"]             = ("Option 6 — Change Activation Channel",  "Tùy chọn 6 — Thay Đổi Kênh Kích Hoạt"),
            ["Act7"]             = ("Option 7 — Check & Remove KMS Settings", "Tùy chọn 7 — Kiểm Tra & Xóa Cài Đặt KMS"),
            ["Act8"]             = ("Option 8 — KMS Activation", "Tùy chọn 8 — Kích Hoạt KMS"),
            ["O8KMS_DESC1"]      = ("KMS (Key Management Service) is an enterprise volume-licensing activation channel. A KMS client contacts a KMS host on the corporate network to activate.",
                                    "KMS (Dịch Vụ Quản Lý Key) là kênh kích hoạt cấp phép doanh nghiệp. KMS client liên hệ KMS host trên mạng nội bộ để kích hoạt."),
            ["O8KMS_DESC2"]      = ("Requirements: GVLK key installed · KMS host reachable on TCP 1688 · DNS SRV record (_VLMCS._TCP) or manual host · System clock within 4 hours of KMS host.",
                                    "Yêu cầu: Đã cài key GVLK · KMS host truy cập được qua TCP 1688 · Bản ghi DNS SRV (_VLMCS._TCP) hoặc nhập thủ công · Đồng hồ hệ thống lệch tối đa 4 giờ so với KMS host."),
            ["O8KMS_DESC3"]      = ("KMS activation expires after 180 days and renews automatically every 7 days while connected to the corporate network.",
                                    "Kích hoạt KMS hết hạn sau 180 ngày và tự động gia hạn mỗi 7 ngày khi kết nối mạng nội bộ."),
            ["O8KMS_WARN_NOTVOLUME"] = ("⚠  Current channel is not VOLUME_KMSCLIENT. A GVLK (Generic Volume License Key) must be installed first. This tool will offer to install the correct GVLK for your edition.",
                                         "⚠  Kênh hiện tại không phải VOLUME_KMSCLIENT. Cần cài key GVLK (Key Bản Quyền Chung) trước. Công cụ này sẽ đề xuất cài GVLK đúng cho ấn bản của bạn."),
            ["O8KMS_WARN_KMSHOST"] = ("⚠  This machine is a KMS HOST (VOLUME_KMS channel) — not a KMS client. This option targets KMS clients only.",
                                       "⚠  Máy này là KMS HOST (kênh VOLUME_KMS) — không phải KMS client. Tùy chọn này chỉ dành cho KMS client."),

            // ── Option 6 — pre-flight step labels ────────────────────────────────
            ["O8KMS_CHK_CHANNEL"]  = ("Step 1: Checking activation channel...",  "Bước 1: Kiểm tra kênh kích hoạt..."),
            ["O8KMS_CHK_GVLK"]    = ("Step 2: Checking installed key (GVLK)...", "Bước 2: Kiểm tra key đã cài (GVLK)..."),
            ["O8KMS_CHK_DNS"]     = ("Step 3: Searching for KMS host via DNS SRV (_VLMCS._TCP)...",
                                      "Bước 3: Tìm KMS host qua DNS SRV (_VLMCS._TCP)..."),
            ["O8KMS_CHK_PORT"]    = ("Step 4: Testing connection to KMS host on TCP 1688...",
                                      "Bước 4: Kiểm tra kết nối đến KMS host trên TCP 1688..."),
            ["O8KMS_CHK_CLOCK"]   = ("Step 5: Checking system clock...",          "Bước 5: Kiểm tra đồng hồ hệ thống..."),
            ["O8KMS_CHK_ACTIVATE"] = ("Step 6: Activating via slmgr /ato...",    "Bước 6: Kích hoạt qua slmgr /ato..."),

            // ── Option 6 — GVLK check / auto-install ─────────────────────────────
            ["O8KMS_GVLK_OK"]        = ("GVLK detected: ",        "Đã phát hiện GVLK: "),
            ["O8KMS_GVLK_MISSING"]   = ("⚠  Installed key is not a GVLK. KMS activation will fail without a valid GVLK.",
                                         "⚠  Key đã cài không phải GVLK. Kích hoạt KMS sẽ thất bại nếu không có GVLK hợp lệ."),
            ["O8KMS_GVLK_FOUND_KEY"] = ("GVLK for this edition:", "GVLK cho ấn bản này:"),
            ["O8KMS_GVLK_CONFIRM"]   = ("Type  OK  to install this GVLK and switch to KMS channel:",
                                         "Nhập  OK  để cài GVLK này và chuyển sang kênh KMS:"),
            ["O8KMS_GVLK_INSTALLING"] = ("Installing GVLK...",    "Đang cài GVLK..."),
            ["O8KMS_GVLK_DONE"]      = ("GVLK installed. Proceeding with KMS activation.",
                                         "Đã cài GVLK. Tiếp tục kích hoạt KMS."),
            ["O8KMS_GVLK_NOMAP"]     = ("No GVLK found for this edition in the database. Contact your IT administrator.",
                                         "Không tìm thấy GVLK cho ấn bản này trong cơ sở dữ liệu. Liên hệ quản trị viên CNTT."),
            ["O8KMS_GVLK_CANCELED"]  = ("GVLK installation canceled.", "Đã hủy cài đặt GVLK."),

            // ── Option 6 — DNS / manual host / port / clock ───────────────────────
            ["O8KMS_DNS_FOUND"]      = ("KMS host found via DNS: ",          "Đã tìm thấy KMS host qua DNS: "),
            ["O8KMS_DNS_FAIL"]       = ("DNS auto-discovery failed. No _VLMCS._TCP SRV record found.",
                                        "Tìm kiếm DNS tự động thất bại. Không tìm thấy bản ghi SRV _VLMCS._TCP."),
            ["O8KMS_MANUAL_LABEL"]   = ("Enter KMS server hostname or IP:",   "Nhập hostname hoặc IP của KMS server:"),
            ["O8KMS_MANUAL_HINT"]    = ("Leave blank to cancel.",              "Để trống để hủy."),
            ["O8KMS_SKMS_PERSIST"]   = ("TCP 1688 reachable — setting KMS server permanently (slmgr /skms).",
                                        "TCP 1688 truy cập được — đặt KMS server vĩnh viễn (slmgr /skms)."),
            ["O8KMS_SKMS_NOPERSIST"] = ("TCP 1688 unreachable — KMS server NOT persisted. Try again when server is reachable.",
                                        "TCP 1688 không truy cập được — KMS server KHÔNG được lưu. Thử lại khi server truy cập được."),
            ["O8KMS_PORT_OK"]        = ("TCP 1688 reachable on ",             "TCP 1688 truy cập được trên "),
            ["O8KMS_PORT_FAIL"]      = ("⚠  TCP 1688 unreachable on ",        "⚠  TCP 1688 không truy cập được trên "),
            ["O8KMS_CLOCK_WARN"]     = ("⚠  Could not verify clock sync. If activation fails with 0xC004F06C, check your system time.",
                                        "⚠  Không thể xác minh đồng bộ đồng hồ. Nếu kích hoạt thất bại với 0xC004F06C, hãy kiểm tra đồng hồ hệ thống."),

            // ── Option 6 — activation results & KMS error diagnosis ───────────────
            ["O8KMS_SUCCESS"]         = ("KMS activation succeeded!", "Kích hoạt KMS thành công!"),
            ["O8KMS_SUCCESS2"]        = ("This activation is valid for 180 days and renews automatically while connected to the corporate network.",
                                         "Kích hoạt này có hiệu lực 180 ngày và tự động gia hạn khi kết nối mạng nội bộ."),
            ["O8KMS_FAIL"]            = ("KMS activation failed.", "Kích hoạt KMS thất bại."),
            ["O8KMS_DIAG_COUNT"]      = ("Diagnosis: KMS Count Insufficient (0xC004F038) — KMS pool requires ≥25 Windows client activations (or ≥5 Server). Contact your IT administrator to add more machines.",
                                         "Chẩn đoán: Số Lượng KMS Không Đủ (0xC004F038) — pool KMS cần ≥25 kích hoạt Windows client (hoặc ≥5 Server). Liên hệ quản trị viên để thêm máy."),
            ["O8KMS_DIAG_NOTENABLED"] = ("Diagnosis: KMS Host Not Responding (0xC004F039) — KMS host is not enabled or firewall is blocking TCP port 1688. Check network and firewall settings.",
                                         "Chẩn đoán: KMS Host Không Phản Hồi (0xC004F039) — KMS host không hoạt động hoặc tường lửa chặn cổng TCP 1688. Kiểm tra mạng và cài đặt tường lửa."),
            ["O8KMS_DIAG_HOSTNACT"]   = ("Diagnosis: KMS Host Not Activated (0xC004F041) — the KMS host itself must be activated first. Contact your IT administrator.",
                                         "Chẩn đoán: KMS Host Chưa Kích Hoạt (0xC004F041) — bản thân KMS host cần được kích hoạt trước. Liên hệ quản trị viên CNTT."),
            ["O8KMS_DIAG_WRONGHOST"]  = ("Diagnosis: Wrong KMS Host (0xC004F042) — the KMS host cannot activate this product. Verify the KMS host is configured for your OS/edition.",
                                         "Chẩn đoán: KMS Host Sai (0xC004F042) — KMS host không thể kích hoạt sản phẩm này. Kiểm tra cấu hình KMS host cho OS/ấn bản của bạn."),
            ["O8KMS_DIAG_CLOCK"]      = ("Diagnosis: Clock Skew (0xC004F06C) — system time differs too much from KMS host (limit: 4 hours). Sync your system clock via NTP.",
                                         "Chẩn đoán: Lệch Đồng Hồ (0xC004F06C) — thời gian hệ thống lệch quá nhiều so với KMS host (giới hạn: 4 giờ). Đồng bộ đồng hồ hệ thống qua NTP."),
            ["O8KMS_DIAG_NOCONTACT"]  = ("Diagnosis: No KMS Reachable (0xC004F074) — all KMS hosts returned errors. Check DNS, network, and Application Event Log (Event ID 12288).",
                                         "Chẩn đoán: Không Liên Hệ Được KMS (0xC004F074) — tất cả KMS host đều trả về lỗi. Kiểm tra DNS, mạng, và Nhật Ký Sự Kiện (Event ID 12288)."),
            ["O8KMS_DIAG_DNS"]        = ("Diagnosis: DNS Name Not Found (0x8007007B / 0x8007232B / 0x8007251D) — KMS SRV record missing in DNS or no KMS host installed.",
                                         "Chẩn đoán: Không Tìm Thấy Tên DNS (0x8007007B / 0x8007232B / 0x8007251D) — thiếu bản ghi SRV KMS trong DNS hoặc chưa cài KMS host."),
            ["O8KMS_DIAG_VOLK"]       = ("Diagnosis: Invalid Volume License Key (0xC004F035) — the installed key is not a valid GVLK for volume activation. Install the correct GVLK first.",
                                         "Chẩn đoán: Key Bản Quyền Số Lượng Lớn Không Hợp Lệ (0xC004F035) — key đã cài không phải GVLK hợp lệ để kích hoạt số lượng lớn. Cài GVLK đúng trước."),
            ["O8KMS_REF_URL"]         = ("Reference: https://learn.microsoft.com/en-us/troubleshoot/windows-server/licensing-and-activation/troubleshoot-activation-error-codes",
                                         "Tham khảo: https://learn.microsoft.com/en-us/troubleshoot/windows-server/licensing-and-activation/troubleshoot-activation-error-codes"),

            // ── Option 6 — KMS Panel UI strings ──────────────────────────────────
            ["O8KMS_PANEL_TITLE"]     = ("KMS Activation",                   "Kích Hoạt KMS"),
            ["O8KMS_PROCEED"]         = ("Proceed with Activation",          "Tiến Hành Kích Hoạt"),
            ["O8KMS_CANCEL"]          = ("Cancel",                            "Hủy"),
            ["O8KMS_CANCELED"]        = ("KMS activation canceled.",          "Đã hủy kích hoạt KMS."),

            // ── Option 6 — Change Activation Channel ─────────────────────────────
            ["O6CH_DESC"]            = ("Switch your Windows licensing channel. Switching to KMS installs the GVLK for your edition. Switching to RETAIL/MAK opens the key installation flow.",
                                         "Chuyển đổi kênh bản quyền Windows. Chuyển sang KMS sẽ cài GVLK cho ấn bản của bạn. Chuyển sang RETAIL/MAK mở luồng cài key."),
            ["O6CH_CURRENT_CHANNEL"] = ("Current channel:",                         "Kênh hiện tại:"),
            ["O6CH_CURRENT_KEY"]     = ("Current partial key:",                      "Key một phần hiện tại:"),
            ["O6CH_CURRENT_EDITION"] = ("Edition:",                                  "Ấn bản:"),
            ["O6CH_TO_KMS"]          = ("→ Switch to VOLUME_KMSCLIENT (KMS)",        "→ Chuyển sang VOLUME_KMSCLIENT (KMS)"),
            ["O6CH_TO_RETAIL"]       = ("→ Switch to RETAIL / MAK",                  "→ Chuyển sang RETAIL / MAK"),
            ["O6CH_GVLK_LABEL"]      = ("GVLK for this edition:",                    "GVLK cho ấn bản này:"),
            ["O6CH_GVLK_CONFIRM"]    = ("Type  OK  to install this GVLK:",           "Nhập  OK  để cài GVLK này:"),
            ["O6CH_GVLK_INSTALLING"] = ("Installing GVLK…",                          "Đang cài GVLK…"),
            ["O6CH_GVLK_DONE"]       = ("GVLK installed. Redirecting to KMS Activation (Option 8)…",
                                         "Đã cài GVLK. Đang chuyển sang Kích Hoạt KMS (Tùy chọn 8)…"),
            ["O6CH_GVLK_NOMAP"]      = ("No GVLK found for this edition. Contact your IT administrator.",
                                         "Không tìm thấy GVLK cho ấn bản này. Liên hệ quản trị viên IT."),
            ["O6CH_RETAIL_MSG"]      = ("To switch to RETAIL or MAK, install your product key using Option 2 — Test & Install New Key. Note: activation requires internet access to reach Microsoft servers.",
                                         "Để chuyển sang RETAIL hoặc MAK, hãy cài key sản phẩm qua Tùy chọn 2 — Kiểm thử & Cài Key Mới. Lưu ý: cần kết nối internet để kích hoạt với máy chủ Microsoft."),
            ["O6CH_REDIRECT_OPT2"]   = ("Redirecting to Option 2 — Test & Install New Key…",
                                         "Đang chuyển sang Tùy chọn 2 — Kiểm thử & Cài Key Mới…"),
            ["O6CH_REDIRECT_OPT8"]   = ("Redirecting to Option 8 — KMS Activation…",
                                         "Đang chuyển sang Tùy chọn 8 — Kích Hoạt KMS…"),
            ["O6CH_HOST_WARN"]       = ("⚠  This machine is a KMS HOST (VOLUME_KMS channel). This tool targets KMS clients only.",
                                         "⚠  Máy này là KMS HOST (kênh VOLUME_KMS). Công cụ này chỉ dành cho KMS client."),
            ["O6CH_CANCELLED"]       = ("Channel change cancelled.",                 "Đã hủy thay đổi kênh."),
            ["O6CH_PANEL_TITLE"]     = ("Change Activation Channel",                 "Thay Đổi Kênh Kích Hoạt"),
            ["O6CH_CANCEL"]          = ("Cancel",                                    "Hủy"),
            ["O6CH_PROCEED"]         = ("Proceed",                                   "Tiến Hành"),

            // ── Option 7 — Check & Remove KMS Settings ────────────────────────────
            ["O7KMS_DESC"]           = ("View the currently configured KMS server settings and optionally clear them to restore DNS auto-discovery.",
                                         "Xem cài đặt KMS server hiện tại và tùy chọn xóa để khôi phục tự động phát hiện DNS."),
            ["O7KMS_REG_HOST"]       = ("KMS Host (registry):",                      "KMS Host (registry):"),
            ["O7KMS_REG_PORT"]       = ("KMS Port (registry):",                      "KMS Port (registry):"),
            ["O7KMS_DLV_HOST"]       = ("KMS Host (slmgr /dlv):",                   "KMS Host (slmgr /dlv):"),
            ["O7KMS_NOT_SET"]        = ("not set",                                   "chưa đặt"),
            ["O7KMS_DEFAULT_PORT"]   = ("default (1688)",                            "mặc định (1688)"),
            ["O7KMS_NONE_ACTIVE"]    = ("No custom KMS server configured. DNS auto-discovery is active.",
                                         "Chưa có KMS server tùy chỉnh. Tự động phát hiện DNS đang hoạt động."),
            ["O7KMS_CUSTOM_ACTIVE"]  = ("A custom KMS server is currently configured.",
                                         "Đang có KMS server tùy chỉnh được cấu hình."),
            ["O7KMS_CLEAR_LABEL"]    = ("Clear KMS server setting (slmgr /ckms)",    "Xóa cài đặt KMS server (slmgr /ckms)"),
            ["O7KMS_CLEAR_CONFIRM"]  = ("Type  OK  to confirm clearing KMS server:", "Nhập  OK  để xác nhận xóa KMS server:"),
            ["O7KMS_CLEARING"]       = ("Clearing KMS server setting…",              "Đang xóa cài đặt KMS server…"),
            ["O7KMS_CLEARED"]        = ("KMS server setting cleared. Windows will use DNS auto-discovery.",
                                         "Đã xóa cài đặt KMS server. Windows sẽ dùng tự động phát hiện DNS."),
            ["O7KMS_CLEAR_FAILED"]   = ("Failed to clear KMS server setting.",       "Không thể xóa cài đặt KMS server."),
            ["O7KMS_NEXT_OPT8"]      = ("→ Use Option 8 to activate with a new KMS host",
                                         "→ Dùng Tùy chọn 8 để kích hoạt với KMS host mới"),
            ["O7KMS_NEXT_OPT6"]      = ("→ Use Option 6 to change your activation channel",
                                         "→ Dùng Tùy chọn 6 để thay đổi kênh kích hoạt"),
            ["O7KMS_NEXT_DNS"]       = ("→ Windows will attempt DNS SRV auto-discovery on next activation",
                                         "→ Windows sẽ thử tự động phát hiện DNS SRV trong lần kích hoạt tiếp theo"),
            ["O7KMS_PANEL_TITLE"]    = ("KMS Settings",                             "Cài Đặt KMS"),
            ["O7KMS_CLOSE"]          = ("Close",                                    "Đóng"),
            ["O7KMS_CLEAR_BTN"]      = ("Clear KMS Server",                         "Xóa KMS Server"),
        };


        public static string Get(string key) =>
            S.TryGetValue(key, out var v) ? (Current == Lang.EN ? v.EN : v.VIE) : key;
    }
}
